# -*- coding: utf-8 -*-
"""230112 base_ex03 Sharpening filter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vEnu5elrN73VhR8irmday7g0mK-ZM4EW
"""

import cv2
from google.colab.patches import cv2_imshow
import numpy as np

image = cv2.imread('./car.png')

# Creating out sharpening filter
filter = np.array([[-1, -1, -1], [-1, 9, -1], [-1, -1, -1]])

sharpen_img = cv2.filter2D(image, -1, filter)
cv2_imshow(image)
cv2.waitKey(0)
cv2_imshow(sharpen_img)

