# -*- coding: utf-8 -*-
"""230103 ex_06_Image rotation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pb-rxnHcK7ra0JmjQ84f9tdv5gDjr1yE
"""

# !pip install opencv-python==4.5.5.62
import cv2
from google.colab.patches import cv2_imshow

# 이미지 경로
image_path="./IU.jpg"

# 이미지 읽기
image = cv2.imread(image_path)

#이미지 회전
img90 = cv2.rotate(image, cv2.ROTATE_90_CLOCKWISE)  # 시계 방향으로 90도 회전
img180 = cv2.rotate(image, cv2.ROTATE_180)  # 시계 방향으로 180도 회전
img270 = cv2.rotate(image, cv2.ROTATE_90_COUNTERCLOCKWISE)  # 시계 방향으로 270도 회전

cv2_imshow(image)
cv2_imshow(img90)
cv2_imshow(img180)
cv2_imshow(img270)
cv2.waitKey(0)

# 이미지 좌우 및 상하 반전
# 1_좌우 반전 0_상하 반전
dst_temp1 = cv2.flip(image, 1) 
dst_temp2 = cv2.flip(image, 0)

cv2_imshow(dst_temp1)
cv2_imshow(dst_temp2)
cv2.waitKey()

