# -*- coding: utf-8 -*-
"""230111 base_ex02 Gaussian filter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/140H3nYQQXu_IYejSyCS5MFDEht0Y_5kh
"""

import cv2
from google.colab.patches import cv2_imshow
import numpy as np

# 가우시안 필터 적용
img = cv2.imread('./car.png', 0)
print(img.shape)
img_rsize = cv2.resize(img, (640,360))

Gaussian_blurred_1 = np.hstack([
    cv2.GaussianBlur(img_rsize, (3,3), 0),
    cv2.GaussianBlur(img_rsize, (5,5), 0),
    cv2.GaussianBlur(img_rsize, (7,7), 0),
])
cv2_imshow(Gaussian_blurred_1)
cv2.imwrite("gaussian_blur.png", Gaussian_blurred_1)
cv2.waitKey(0)

